<?php
/**
 * Single product short description
 *
 * This template overrides woocommerce/templates/single-product/short-description.php.
 *
 * @see 	    http://docs.woothemes.com/document/template-structure/
 * @version     3.3.0
 */

$post = get_post();
$short_description = apply_filters( 'woocommerce_short_description', $post->post_excerpt );

if ( ! $short_description ) {
	return;
}


?>
<div itemprop="description" class="base-text textwidget description">
	<?php echo $short_description; // phpcs:ignore WordPress.Security.EscapeOutput -- Safe; generated by WooCommerce above. ?>
</div>